AWSTemplateFormatVersion: '2010-09-09'
Description: 'Base Template for deploying a dockerized application'

Parameters:
  Swarm:
    Description: 'Docker Swarm Cluster to use'
    Type: String
  PublishPort:
    Description: 'Port Application is exposing'
    Type: Number
  BillingDivision:
    Type: String
  BillingEnvironment:
    Type: String
  BillingProject:
    Type: String
  BillingEnvId:
    Type: String
  BillingRole:
    Type: String
  TargetGroupTags:
    Type: CommaDelimitedList
  SecurityGroups:
    Description: 'Security Group to use for the Application Load Balancer'
    Type: 'String'
    Default: 'sg-6c8a911b'
  SubnetAZ1:
    Type: 'String'
    Default: 'subnet-5c4a6c2a'
  SubnetAZ2:
    Type: 'String'
    Default: 'subnet-2e4e3c76'
  SubnetAZ3:
    Type: 'String'
    Default: 'subnet-d21067f8'
  SubnetAZ4:
    Type: 'String'
    Default: 'subnet-af765192'
  TargetVpcId:
    Type: 'AWS::EC2::VPC::Id'
    Default: 'vpc-6b3cfe0c'
  DnsZoneName:
    Type: String
    Default: 'mldev.cloud.'
  Certificate:
    Type: String
    Default: 'arn:aws:acm:us-east-1:999447569257:certificate/f52216d5-601a-45b8-9748-939b8356f1b0'
  AppLoadBalancerScheme:
    Description: 'Specifies if the Load Balancer is internal or internet-facing'
    Type: String
    Default: 'internet-facing'
    AllowedValues:
      - 'internal'
      - 'internet-facing'

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: "/status"
      Protocol: HTTP
      Port: !Ref PublishPort
      VpcId: !Ref TargetVpcId
      Name: !Ref 'AWS::StackName'
      Tags:
        - Key: swarm
          Value: !Ref Swarm
        - Key: PublishPort
          Value: !Ref PublishPort
  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref 'AWS::StackName'
      Scheme: !Ref AppLoadBalancerScheme
      SecurityGroups:
        - !Ref SecurityGroups
      Subnets:
        - !Ref SubnetAZ1
        - !Ref SubnetAZ2
        - !Ref SubnetAZ3
        - !Ref SubnetAZ4        
      Tags:
        - Key: division 
          Value: !Ref BillingDivision
        - Key: project 
          Value: !Ref BillingProject
        - Key: environment 
          Value: !Ref BillingEnvironment
        - Key: envid 
          Value: !Ref BillingEnvId
        - Key: role
          Value: !Ref BillingRole
  AppLoadBalancerListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: TargetGroup
      LoadBalancerArn:
        Ref: AppLoadBalancer
      Port: '80'
      Protocol: HTTP
  AppLoadBalancerListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
      - CertificateArn: !Ref Certificate
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: TargetGroup
      LoadBalancerArn:
        Ref: AppLoadBalancer
      Port: '443'
      Protocol: HTTPS
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget: 
        DNSName: !GetAtt AppLoadBalancer.DNSName
        HostedZoneId: !GetAtt AppLoadBalancer.CanonicalHostedZoneID
      Name: !Join ['.', [!Ref 'AWS::StackName', !Ref 'DnsZoneName']]
      Type: 'A'
      HostedZoneName: !Ref DnsZoneName

Outputs:
  StackUrl:
    Description: Url to Deployed Stack
    Value: !Join ['', ['https://', !Ref 'DNSRecord']]
